# Week 6 activities: Data wrangling using pandas

# Setup

In [1]:
# packages
import pandas as pd
import numpy as np
import os

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# Load the data: you'll need to edit your path
# I recommend moving this notebook into your "myactivities" repo, 
# creating a folder in that repo for data, moving the data there, and loading from there

In [2]:
os.getcwd()

'c:\\Users\\erobl\\datascience-foundations\\ppol5203_f26_myactivities\\code'

In [5]:
df = pd.read_csv("Data/childnoinsur_complete.csv")
df.head()

,State,Race,Year,uninsured_rate,Census_Division
0,Wyoming,Non-Hispanic White,2018,0.07,Mountain
1,Wyoming,Hispanic or Latino,2018,0.06,Mountain
2,Wyoming,Black or African American,2018,0.02,Mountain
3,Wyoming,Asian and Pacific Islander,2018,0.02,Mountain
4,Wisconsin,Two or more races,2018,0.02,East North Central

# Activity 1: attributes of dataframes

Using the data loaded above, answer the following questions:

A. What are the unique racial/ethnic categories in the data?

B. What is the maximum and minimum child uninsurance rate?

C. What is the earliest and latest year in the data?

D. Which state(s) has the most observations? Which state(s) has the fewest? (note: this version of the dataset omits state-row-categories with missing data on the uninsurance rate; next week, we'll work with a version that retains observations with those missing values)

*Hint*: for part D you may want to use sort_values() - documentation is here: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sort_values.html

In [26]:
## your code here
df.Race.value_counts
set(df.Race)


df_max = df['uninsured_rate'].max()
df_max

df_min = df['uninsured_rate'].min()
df_min

df_year_early = df['Year'].min()
df_year_early

df_year_late = df['Year'].max()
df_year_late

df_observations = df.State.value_counts().sort_values(ascending=False)
df_observations

df_observations.max()
df_observations.min()

<bound method IndexOpsMixin.value_counts of 0                     Non-Hispanic White
1                     Hispanic or Latino
2              Black or African American
3             Asian and Pacific Islander
4                      Two or more races
                      ...
1709    American Indian or Alaska Native
1710           Black or African American
1711                  Hispanic or Latino
1712                  Non-Hispanic White
1713                   Two or more races
Name: Race, Length: 1714, dtype: object>

{'American Indian or Alaska Native',
 'Asian and Pacific Islander',
 'Black or African American',
 'Hispanic or Latino',
 'Non-Hispanic White',
 'Two or more races'}

np.float64(0.24)

np.float64(0.01)

np.int64(2017)

np.int64(2024)

State
North Carolina    42
Washington        42
Oklahoma          42
California        42
Arizona           42
New York          41
Minnesota         41
Texas             40
Colorado          40
Michigan          40
Alabama           39
Illinois          39
Ohio              39
Pennsylvania      39
Virginia          38
Wisconsin         38
Connecticut       38
Kentucky          38
Indiana           38
New Jersey        38
Tennessee         37
Oregon            37
Iowa              37
Missouri          36
New Mexico        36
South Carolina    36
Florida           36
Georgia           36
Maryland          36
Nevada            36
Massachusetts     35
Kansas            35
Louisiana         34
Nebraska          33
Arkansas          33
Delaware          31
Idaho             31
Hawaii            30
Alaska            30
Rhode Island      29
Montana           28
Utah              28
Maine             27
Mississippi       26
New Hampshire     25
West Virginia     24
South Dakota      24
North Dakota      22
Wyoming           16
Vermont           14
Name: count, dtype: int64

np.int64(42)

np.int64(14)

# Activity 2: selecting and filtering

A. Subset the data to the State == `California`. Store the resulting dataframe as `ca_df` and use the `shape` command to print the dimensions

In [58]:
## your code here
ca_df = df[df["State"] == "California"]
ca_df.head()
ca_df.shape

,State,Race,Year,uninsured_rate,Census_Division
227,California,Two or more races,2018,0.02,Pacific
228,California,Non-Hispanic White,2018,0.02,Pacific
229,California,Hispanic or Latino,2018,0.04,Pacific
230,California,Black or African American,2018,0.02,Pacific
231,California,Asian and Pacific Islander,2018,0.02,Pacific

(42, 5)

B. Use list comprehension and the `columns` attribute to create a list of columns, called `cols_keep` that excludes the following two columns: 
- `State`
- `Census_Division`

Print the list. It should contain columns for Race, Year, and uninsured_rate

In [61]:
## your code here
cols_keep = df[df.columns[[0,4]]].columns.to_list()
cols_keep

['State', 'Census_Division']

C. Use the `cols_keep` list to create a new dataset, `ca_df_clean` that removes those two columns. Print the head

In [62]:
## your code here
ca_df_clean = ca_df.drop(columns=cols_keep)
ca_df_clean.head()

                           Race  Year  uninsured_rate
227           Two or more races  2018            0.02
228          Non-Hispanic White  2018            0.02
229          Hispanic or Latino  2018            0.04
230   Black or African American  2018            0.02
231  Asian and Pacific Islander  2018            0.02

D. Write a user-defined function, `subset_onerace` that takes in three arguments:
- A string for a racial/ethnic group
- A string representing the name of the race/ethnicity column
- A dataframe

And subset the data to rows of data for that race/ethnicity

In [41]:
## your code here
def subset_onerace(race, race_name, df):
    return df[df[race_name] == race]

E. Use that user-defined function to return the rows for `American Indian or Alaska Native`, ordered by year from lowest to highest. Has the uninsurance rate among children gone up or down over time?

In [64]:
## your code here
df_ameri = subset_onerace("American Indian or Alaska Native","Race",df = ca_df_clean)
df_ameri.sort_values(by = "Year")

                                  Race  Year  uninsured_rate
278   American Indian or Alaska Native  2017            0.08
232   American Indian or Alaska Native  2018            0.08
1203  American Indian or Alaska Native  2019            0.07
1250  American Indian or Alaska Native  2021            0.05
723   American Indian or Alaska Native  2022            0.05
1681  American Indian or Alaska Native  2023            0.06
770   American Indian or Alaska Native  2024            0.04

F. Using list comprehension, iterate over the unique race/ethnicity groups in `ca_df_clean` and apply that function to create a subset of rows ordered by year for that group; the result will be a list of dataframes

Print the result; what patterns do you notice?

In [68]:
## your code here
separate_groups = [
    subset_onerace(race=group, race_name="Race", df=ca_df_clean).sort_values(by="Year")
    for group in ca_df_clean["Race"].unique()
]

separate_groups

[                   Race  Year  uninsured_rate
 273   Two or more races  2017            0.02
 227   Two or more races  2018            0.02
 1198  Two or more races  2019            0.02
 1256  Two or more races  2021            0.03
 728   Two or more races  2022            0.03
 1686  Two or more races  2023            0.03
 775   Two or more races  2024            0.03,
                     Race  Year  uninsured_rate
 274   Non-Hispanic White  2017            0.02
 228   Non-Hispanic White  2018            0.02
 1199  Non-Hispanic White  2019            0.03
 1257  Non-Hispanic White  2021            0.02
 727   Non-Hispanic White  2022            0.02
 1685  Non-Hispanic White  2023            0.02
 774   Non-Hispanic White  2024            0.02,
                     Race  Year  uninsured_rate
 275   Hispanic or Latino  2017            0.04
 229   Hispanic or Latino  2018            0.04
 1200  Hispanic or Latino  2019            0.04
 1247  Hispanic or Latino  2021            0.04
 726   Hispanic or Latino  2022            0.04
 1684  Hispanic or Latino  2023            0.04
 773   Hispanic or Latino  2024            0.04,
                            Race  Year  uninsured_rate
 276   Black or African American  2017            0.03
 230   Black or African American  2018            0.02
 1201  Black or African American  2019            0.02
 1248  Black or African American  2021            0.03
 725   Black or African American  2022            0.03
 1683  Black or African American  2023            0.04
 772   Black or African American  2024            0.03,
                             Race  Year  uninsured_rate
 277   Asian and Pacific Islander  2017            0.03
 231   Asian and Pacific Islander  2018            0.02
 1202  Asian and Pacific Islander  2019            0.03
 1249  Asian and Pacific Islander  2021            0.03
 724   Asian and Pacific Islander  2022            0.02
 1682  Asian and Pacific Islander  2023            0.03
 771   Asian and Pacific Islander  2024            0.02,
                                   Race  Year  uninsured_rate
 278   American Indian or Alaska Native  2017            0.08
 232   American Indian or Alaska Native  2018            0.08
 1203  American Indian or Alaska Native  2019            0.07
 1250  American Indian or Alaska Native  2021            0.05
 723   American Indian or Alaska Native  2022            0.05
 1681  American Indian or Alaska Native  2023            0.06
 770   American Indian or Alaska Native  2024            0.04]

# Activity 3: creating and recoding variables

A. Going back to the full dataset, `df`, create a new variable in the dataset, `race_simplified`, that:

- Converts the string to lowercase
- Replaces spaces with _ 

Use `pd.crosstab` with the two variables to make sure the recoding worked

In [73]:
## your code here
df = df.assign(
    race_simplified=df["Race"].str.lower().str.replace(" ", "_")
)

pd.crosstab(df["Race"], df["race_simplified"])

race_simplified,american_indian_or_alaska_native,asian_and_pacific_islander,black_or_african_american,hispanic_or_latino,non-hispanic_white,two_or_more_races
Race,,,,,,
American Indian or Alaska Native,153,0,0,0,0,0
Asian and Pacific Islander,0,274,0,0,0,0
Black or African American,0,0,288,0,0,0
Hispanic or Latino,0,0,0,320,0,0
Non-Hispanic White,0,0,0,0,350,0
Two or more races,0,0,0,0,0,329

B. In the full dataset, use `np.mean` to find the nationwide average uninsurance rate. Create a variable, `ur_demean` that subtracts that national average from each individual `uninsured_rate`

Use .describe() to confirm the de-meaning worked (the overall variable mean should be very close to zero and min and max should change)

In [78]:
## your code here
df['ur_demean'] = df.uninsured_rate - np.mean(df.uninsured_rate) 
df['ur_demean'].describe()

count    1.714000e+03
mean    -6.606928e-18
std      3.586915e-02
min     -4.419487e-02
25%     -2.419487e-02
50%     -1.419487e-02
75%      1.580513e-02
max      1.858051e-01
Name: ur_demean, dtype: float64

C. In the full dataset, use `np.select` to create a new variable, `type_statename` that codes state names into two categories:
    
    - two_words: if the name has multiple words (eg North Carolina, New Jersey, etc)
    - one_word: if the name has a single word
        
Hint: you can do this by checking whether the name string contains any spaces, comparing the length of the string to the number of alpha characters, or another approach

Spot check your work using the `sample` command

In [ ]:
## your code here
type_statename = np.select()

# Activity 4: grouping and aggregation

A. Group the dataset by `Census_Division`. Use a for loop to print the group names

In [80]:
## your code here
df_census_division = df.groupby("Census_Division")
for group, data in df_census_division:
    print("Census Division: " + group)

Census Division: East North Central
Census Division: East South Central
Census Division: Middle Atlantic
Census Division: Mountain
Census Division: New England
Census Division: Pacific
Census Division: South Atlantic
Census Division: West North Central
Census Division: West South Central

B. Use `get_group` to extract the Pacific region group and find the mean `uninsured_rate` for states/years/racial/ethnic groups in that group

In [95]:
## your code here
df.head()
pacific_group = df_census_division.get_group("Pacific")
pacific_group

pacific_mean = pacific_group.groupby(['State','Year', 'Race'])['uninsured_rate'].mean()
pacific_mean

,State,Race,Year,uninsured_rate,Census_Division,race_simplified,ur_demean
0,Wyoming,Non-Hispanic White,2018,0.07,Mountain,non-hispanic_white,0.015805
1,Wyoming,Hispanic or Latino,2018,0.06,Mountain,hispanic_or_latino,0.005805
2,Wyoming,Black or African American,2018,0.02,Mountain,black_or_african_american,-0.034195
3,Wyoming,Asian and Pacific Islander,2018,0.02,Mountain,asian_and_pacific_islander,-0.034195
4,Wisconsin,Two or more races,2018,0.02,East North Central,two_or_more_races,-0.034195

,State,Race,Year,uninsured_rate,Census_Division,race_simplified,ur_demean
15,Washington,Two or more races,2018,0.02,Pacific,two_or_more_races,-0.034195
16,Washington,Non-Hispanic White,2018,0.02,Pacific,non-hispanic_white,-0.034195
17,Washington,Hispanic or Latino,2018,0.04,Pacific,hispanic_or_latino,-0.014195
18,Washington,Black or African American,2018,0.02,Pacific,black_or_african_american,-0.034195
19,Washington,Asian and Pacific Islander,2018,0.03,Pacific,asian_and_pacific_islander,-0.024195
...,...,...,...,...,...,...,...
1704,Alaska,American Indian or Alaska Native,2023,0.17,Pacific,american_indian_or_alaska_native,0.115805
1705,Alaska,Asian and Pacific Islander,2023,0.04,Pacific,asian_and_pacific_islander,-0.014195
1706,Alaska,Hispanic or Latino,2023,0.06,Pacific,hispanic_or_latino,0.005805
1707,Alaska,Non-Hispanic White,2023,0.04,Pacific,non-hispanic_white,-0.014195
1708,Alaska,Two or more races,2023,0.07,Pacific,two_or_more_races,0.015805

State       Year  Race
Alaska      2017  Non-Hispanic White                  0.05
                  Two or more races                   0.13
            2018  American Indian or Alaska Native    0.15
                  Asian and Pacific Islander          0.07
                  Hispanic or Latino                  0.11
                                                      ...
Washington  2024  Asian and Pacific Islander          0.04
                  Black or African American           0.03
                  Hispanic or Latino                  0.05
                  Non-Hispanic White                  0.03
                  Two or more races                   0.03
Name: uninsured_rate, Length: 181, dtype: float64

C. Going back to the full dataset, group by `Census_Division` and find the mean uninsurance rate within that group across all states/years. Was the Mountain region higher or lower than other regions in terms of its child uninsurance rate? Which region has the lowest uninsurance rate?

In [ ]:
## your code here

D. Use `groupby` and the built-in `idxmax` aggregation function to:
    
- Group by race/ethnic group (`Race`)
- Find the year and state with the highest uninsurance rate for that race/ethnic group

Hint: there are multiple approaches for how to pull the columns tied to the row with the maximum uninsurance rate, including .loc and sort_values()

In [ ]:
## your code here

E. Use `groupby`, `agg`, and a lambda function to:

- Group by race/ethnic group (`Race`)
- Find the interquartile range of uninsurance rates for each race/ethnicity group across states and years. Which groups vary the most?

In [ ]:
## your code here